spring.application.name=eureka_server
server.port=8761

# Since it is a server, it shouldn't try to register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=true
spring.boot.admin.context-path=/admin