spring.application.name=payment-service
# spring.config.import=file:./.env[.properties]
# Replace with your actual full path
# spring.config.import=file:/Users/souravsharma/Projects/WebCom/payment_service/.env[.properties]

razor.key.id=${RAZOR_KEY_ID}

razor.key.secret=${RAZOR_KEY_SECRET}

server.port=${SERVER_PORT}
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

