spring.application.name=customer-service

# POSTGRESSSQL (dev) datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / Hibernate (dev)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# # OPTIONAL: LETTUCE SPECIFIC TUNING CONFIGURATIONS
# # Configures connection timeout threshold (e.g., 5000 milliseconds)
# spring.data.redis.timeout=5000ms

# # Configures Lettuce Connection Pool Metrics
# spring.data.redis.lettuce.pool.max-active=8
# spring.data.redis.lettuce.pool.max-idle=8
# spring.data.redis.lettuce.pool.min-idle=0


# allow schema/data initialization from schema.sql / data.sql
spring.sql.init.mode=always



server.port=${SERVER_PORT}


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

## here below we are using an environmental variable in our properties file
# eureka.username=${EUREKA_USERNAME:eureka}
# eureka.password=${EUREKA_PASSWORD:password}
# temporary
# eureka.client.register-with-eureka=false
# eureka.client.fetch-registry=false

# Temporarily disable Redis connection
# redis.enabled=false


# graphql
spring.graphql.http.path=/graphql
# enabling graphiql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/igraphql
spring.graphql.cors.allowed-origin-patterns=*