spring.application.name=customer_service

# H2 (dev) datasource
spring.datasource.url=jdbc:h2:mem:customerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate (dev)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# allow schema/data initialization from schema.sql / data.sql
spring.sql.init.mode=always


eureka.instance.hostname=localhost
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
server.port=8081

# Link to the Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

## here below we are using an environmental variable in our properties file
# eureka.username=${EUREKA_USERNAME:eureka}
# eureka.password=${EUREKA_PASSWORD:password}
# temporary
# eureka.client.register-with-eureka=false
# eureka.client.fetch-registry=false

# Temporarily disable Redis connection
# redis.enabled=false


# graphql
spring.graphql.http.path=/graphql
# enabling graphiql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/igraphql
spring.graphql.cors.allowed-origin-patterns=*